[package]
name = "underground_accept_bot"
version = "0.1.0"
edition = "2024"

[dependencies]
teloxide = { version = "0.12", features = ["macros"] }
tokio = { version = "1.0", features = ["rt-multi-thread", "macros"] }
dotenv = "0.15"
log = "0.4"
pretty_env_logger = "0.5"
dptree = "0.3"
